### ISSUE TITLE
q Language server keeps reporting errors randomly

### ISSUE THREAD

**Issue by EugeneKallis** [jshinonome/vscode-q#66]
I dont understand what language server even does but when i load a q file my Output tab will popup on q Language server and display an error.

```
TypeError: a.default.matchFile is not a function
    at c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\server.js:1:54427
    at Array.forEach (<anonymous>)
    at d.onDidChangeWatchedFiles (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\server.js:1:54373)
    at c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\server.js:1:90236
    at c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\server.js:1:90454
    at Immediate.<anonymous> (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\server.js:1:92002)
    at processImmediate (node:internal/timers:464:21)
[Info  - 12:12:45 PM] Connection to server got closed. Server will restart.
[Error - 12:12:45 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:133947)
	at Object.dispose (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:214119)
	at b.handleConnectionClosed (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:214332)
	at b.handleConnectionClosed (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:274720)
	at t (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:212421)
	at r.invoke (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:135560)
	at o.fire (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:136321)
	at X (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:123205)
	at r.invoke (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:135560)
	at o.fire (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:136321)
	at d.fireClose (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:144202)
	at ChildProcess.<anonymous> (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:155163)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
[Error - 12:12:45 PM] Request textDocument/semanticTokens/full failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:133947)
	at Object.dispose (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:214119)
	at b.handleConnectionClosed (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:214332)
	at b.handleConnectionClosed (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:274720)
	at t (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:212421)
	at r.invoke (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:135560)
	at o.fire (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:136321)
	at X (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:123205)
	at r.invoke (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:135560)
	at o.fire (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:136321)
	at d.fireClose (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:144202)
	at ChildProcess.<anonymous> (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:155163)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
[Error - 12:12:45 PM] Request textDocument/hover failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:133947)
	at Object.dispose (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:214119)
	at b.handleConnectionClosed (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:214332)
	at b.handleConnectionClosed (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:274720)
	at t (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:212421)
	at r.invoke (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:135560)
	at o.fire (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:136321)
	at X (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:123205)
	at r.invoke (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:135560)
	at o.fire (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:136321)
	at d.fireClose (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:144202)
	at ChildProcess.<anonymous> (c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\client.js:2:155163)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
[Info  - 12:12:46 PM] Initializing q Lang Server at file:///c%3A/git/exdb
Initializing q Lang Server at file:///c%3A/git/exdb
Loaded build-in functions
[Info  - 12:54:14 PM] Received file change event(s)
c:\Users\<user>\.vscode\extensions\jshinonome.vscode-q-2.5.2\dist\server.js:1
```

**Comment by jshinonome** [comment]
Does this happen to any q file? Or one specific q file? What is the error message before this TypeError(first line)?

**Comment by jshinonome** [comment]
Tried mine on windows, similar error message, will take a look.

**Comment by jshinonome** [comment]
I have made a release v2.5.3, let me know if it works.

**Comment by EugeneKallis** [comment]
awesome, i just tried it and dont see error anymore. If it comes up again ill let you know but ill close this for now.
