### ISSUE TITLE
cannot start language server

### ISSUE THREAD

**Issue by xzhai12** [jshinonome/vscode-q#92]
Hi boss, just got this error since one or two days ago - 

```

Node.js v18.15.0
[Info  - 14:22:43] Connection to server got closed. Server will restart.
[Error - 14:22:43] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 14:22:43] q Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 14:22:43] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Trace - 14:22:43] Sending request 'initialize - (0)'.
Initializing q Lang Server at file:///home/uu/research/clientanalysis
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /home/uu/.vscode-server/extensions/jshinonome.vscode-q-3.1.6/dist/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:241:25)
      at /home/uu/.vscode-server/extensions/jshinonome.vscode-q-3.1.6/dist/server.js:1:271638
      at /home/uu/.vscode-server/extensions/jshinonome.vscode-q-3.1.6/dist/server.js:1:271862
      at new Promise (<anonymous>) {
    input: '/home/uu/.vscode-server/extensions/jshinonome.vscode-q-3.1.6/dist/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}
```

Any idea what it might be? 

Your product user and a fan,
Sheldon

**Comment by xzhai12** [comment]
after a bit testing, I can confirm it's caused by VSCode most recent update.

**Comment by jshinonome** [comment]
Is your vscode version 1.82.1? Unfortunately, I can only fix this issue at the start of October.

**Comment by xzhai12** [comment]
> Is your vscode version 1.82.1? Unfortunately, I can only fix this issue at the start of October.

yes the error is found with vscode 1.82.1.
no problem - I can use the previous version for the time being. 
also, I'd like to say that your plug-in is the best among all, and I want to take this opportunity to say thanks to you and your amazing work :)

**Comment by jshinonome** [comment]
Thank you for your kind words:)

**Comment by jshinonome** [comment]
This issue should be fixed, @xzhai12 let me know if any further issue

**Comment by xzhai12** [comment]
thank you, all good now. you are the hero.
